language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew dist"
notifications:
  email: false
deploy:
  - provider: releases
    api_key:
      secure: kMnGPCD6BnzlFoOnKjUBWYWxxvyZJaN3MYZfq0FOIUmp6gle6laAyJuPlBjp+h4aIin8WiNQX7T/lRofGwyUmwxVRMuvZYv/1NF8HVjm79IFGuyCvwxylexdnlj2E8y7+OCud3vBnacrDTVqZnCvne2/uYKwTrHiUeBLH+LpSyzSfNxvhErKLCkfR9XKxW9Zx90JgMn/rfgUG3mHbWSvwaPtiQXh/Y5k6X3kHf4Mmbbkg6tvkXs4vz0lJgzEeYygSLhaAu1VAUSVHpcgRlgt1ygLpz15oobe3fKal13Auz/hbo6hR1e1WNf6bfTSKlnNSBmBOhgYY7izhre1+QWVPqY/UFUOJIELERs/4aAIf4jUE5eA4iz3UTlt/nVgcZQqyozOVQ6Vm+IfsVIzyaSinNGa2mwVzd6Pvdrhh2mvc2pZzOcBHA2gCRVmDnbvj09uLekuwusH10Sya4CdFnRKMPIkg1HUnnbDdFx3LSFPkCRW2L+jmsPp9ubpfh7n4H0sQDvMelJDy0431wyKJAFayscJjaMxxpNpBtfxMitQGiXMTGoc34sFbEanIt4eAZUYMxN41BOwYo2AQAFQuPfaDTzp53D7q/upapCh+lii4VUFF2f67wKRqttfPjA6D8XXxV0byhHvMQYleJkgWqZCXOIyJ1xORhLpVDyYttPV1gA=
    file: 
        - "$TRAVIS_BUILD_DIR/build/distributions/playBinary.zip"
        - "$TRAVIS_BUILD_DIR/build/distributions/playBinary.tar"
    skip_cleanup: true
    overwrite: true
    on:
        tags: true
        repo: EvaluationPS/Portail-Auto-Eval
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: portailautoeval
    on: master
    buildpack: gradle
    skip_cleanup: false
